version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  elasticsearch:
    image: 'elasticsearch:2'
    ports:
      - '9200:9200'
    volumes:
      - 'elastic:/usr/share/elasticsearch/data'
    environment:
      - Des.network.host=0.0.0.0

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'website'
    build: .
    command: bash start_jobs
    volumes:
      - '.:/fractalnoteapi'
    volumes_from:
      - box

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/fractalnoteapi'
      - gems:/gems
    environment:
      ELASTICSEARCH_URL: elasticsearch:9200
    volumes_from:
    - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  redis:
  postgres:
  box:
  gems:
  elastic: